class Cars {
  static const String app_name = "Rent Car";
  static const List<String> CAR_NAMES = [
    "MERCEDES",
    "TESLA",
    "PORSCHE",
    "FERRARI",
    "BMW",
    "JAGUAR",
    "TAHOE",
    "KIA",
    "AUDI",
    "OPEL",
    "BUGATTI",
  ];
  static const List<String> CAR_YEARS = [
    "2021-Year",
    "2021-Year",
    "2018-Year",
    "2017-Year",
    "2019-Year",
    "2018-Year",
    "2020-Year",
    "2019-Year",
    "2020-Year",
    "2020-Year",
    "2019-Year",
  ];
  static const List<String> CAR_INFO = [
    "Mercedes-Benz AG is responsible for the global business of Mercedes-Benz Cars and Mercedes-Benz Vans, with over 170,000 employees worldwide. Ola Källenius is Chairman of the Board of Management of Mercedes-Benz AG. The company focuses on the development, production and sales of passenger cars, vans and vehicle-related services. Furthermore, the company aspires to be the leader in the fields of electric mobility and vehicle software. The product portfolio comprises the Mercedes-Benz brand with the sub-brands of Mercedes-AMG, Mercedes-Maybach, Mercedes-EQ, G-Class and the smart brand. The Mercedes me brand offers access to the digital services from Mercedes-Benz",
    "Tesla was founded in 2003 by a group of engineers who wanted to prove that people didn’t need to compromise to drive electric – that electric vehicles can be better, quicker and more fun to drive than gasoline cars. Today, Tesla builds not only all-electric vehicles but also infinitely scalable clean energy generation and storage products. Tesla believes the faster the world stops relying on fossil fuels and moves towards a zero-emission future, the better.",
    "In post-war Germany, parts were generally in short supply, so the 356 automobile used components from the Volkswagen Beetle, including the engine case from its internal combustion engine, transmission, and several parts used in the suspension. The 356, however, had several evolutionary stages, A, B, and C, while in production, and most Volkswagen-sourced parts were replaced by Porsche-made parts. Beginning in 1954 the 356s engines started utilizing engine cases designed specifically for the 356. The sleek bodywork was designed by Erwin Komenda, who also had designed the body of the Beetle. Porsche's signature designs have, from the beginning, featured air-cooled rear-engine configurations (like the Beetle), rare for other car manufacturers, but producing automobiles that are very well balanced.In 1964, after a fair amount of success in motor-racing with various models including the 550 Spyder, and with the 356 needing a major re-design, the company launched the Porsche 911: another air-cooled, rear-engined sports car, this time with a six-cylinder boxer engine. The team to lay out the body shell design was led by Ferry Porsche's eldest son, Ferdinand Alexander Porsche (F. A.). The design phase for the 911 caused internal problems with Erwin Komenda, who led the body design department until then. F. A. Porsche complained Komenda made unauthorized changes to the design. Company leader Ferry Porsche took his son's drawings to neighbouring chassis manufacturer Reuter. Reuter's workshop was later acquired by Porsche (so-called Werk 2). Afterward, Reuter became a seat manufacturer, today known as Keiper-Recaro.",
    "Ferrari is an Italian automobile company that makes fast luxurious automobile. They are made in Italy and are very expensive. They usually cost \$150,000 - \$1,500,000.Ferraris first car was the Ferrari 125 S.Ferrari has a rich racing history and is a well known premium automobile brand. The fastest street Ferrari is the F50 GT1, which can go over 370 kph (about 222 mph). The most powerful Ferrari is the FXX, which has about 800 horsepower. The FXX is a lighter, improved version of the F60 Enzo; it is Ferrari's most exclusive model. It is basically a race car that you can buy from Ferrari. The automobile is so extreme (completely flat tires, low ride height, and no roadcar safety features such as Airbags) that it cannot be driven on roads legally. Ferrari will keep it for you at their Factory in Maranello in Italy. You can go to Italy and drive it on their private race track, or have it transported to another race track around the world, the same as if you were driving for a racing team. Thirty have been built and all but two were sold to customers for \$2,500,000 each. Ferrari gave one to seven-time Formula 1 World Champion Michael Schumacer, who had driven for Ferrari for ten years when he retired in 2006, having brought Ferrari much success. Ferrari made his FXX different by painting it black. The other twenty-nine are either red or white, with stripes painted in the other colour.",
    "Bayerische Motoren Werke AG, commonly referred to as BMW (German pronunciation: [ˌbeːʔɛmˈveː] (About this soundlisten)), is a German multinational corporate manufacturer of luxury vehicles and motorcycles headquartered in Munich, Bavaria, Germany. The corporation was founded in 1916 as a manufacturer of aircraft engines, which it produced from 1917 until 1918 and again from 1933 to 1945.Automobiles are marketed under the brands BMW, Mini and Rolls-Royce, and motorcycles are marketed under the brand BMW Motorrad. In 2017, BMW was the world's fourteenth-largest producer of motor vehicles, with 2,279,503 vehicles produced. The company has significant motorsport history, especially in touring cars, Formula 1, sports cars and the Isle of Man TT.BMW is headquartered in Munich and produces motor vehicles in Germany, Brazil, China, India, Mexico, the Netherlands, South Africa, the United Kingdom, and the United States. The Quandt family is a long-term shareholder of the company (with the remaining shares owned by public float), following brothers Herbert and Harald Quandt's investments in 1959 which saved the company from bankruptcy.",
    "Jaguar (UK: /ˈdʒæɡjuər/, US: /ˈdʒæɡwɑːr/) is the luxury vehicle brand of Jaguar Land Rover,[1][2] a British multinational car manufacturer with its headquarters in Whitley, Coventry, England. Jaguar Cars was the company that was responsible for the production of Jaguar cars until its operations were fully merged with those of Land Rover to form Jaguar Land Rover on 1 January 2013.Jaguar's business was founded as the Swallow Sidecar Company in 1922, originally making motorcycle sidecars before developing bodies for passenger cars. Under the ownership of S. S. Cars Limited, the business extended to complete cars made in association with Standard Motor Co, many bearing Jaguar as a model name. The company's name was changed from S. S. Cars to Jaguar Cars in 1945. A merger with the British Motor Corporation followed in 1966,[3] the resulting enlarged company now being renamed as British Motor Holdings (BMH), which in 1968 merged with Leyland Motor Corporation and became British Leyland, itself to be nationalised in 1975.Jaguar was spun off from British Leyland and was listed on the London Stock Exchange in 1984, becoming a constituent of the FTSE 100 Index until it was acquired by Ford in 1990. Jaguar has, in recent years, manufactured cars for the British Prime Minister, the most recent delivery being an XJ in May 2010. The company also holds royal warrants from Queen Elizabeth II and Prince Charles.Ford owned Jaguar Cars, also buying Land Rover in 2000, until 2008 when it sold both to Tata Motors. Tata created Jaguar Land Rover as a subsidiary holding company. At operating company level, in 2013 Jaguar Cars was merged with Land Rover to form Jaguar Land Rover Limited as the single design, manufacture, sales company and brand owner for both Jaguar and Land Rover vehicles.Since the Ford ownership era, Jaguar and Land Rover have used joint design facilities in engineering centres at Whitley in Coventry and Gaydon in Warwickshire and Jaguar cars have been assembled in plants at Castle Bromwich and Solihull.",
    "The Chevrolet Tahoe, and its badge engineered GMC Yukon counterpart, are full-size SUVs from General Motors, offered since 1994 and 1991, respectively. Since 1982, Chevrolet and GMC sold two different-sized SUVs under their 'Blazer' and 'Jimmy' nameplates, by introducing the smaller S-10 Blazer and GMC S-15 Jimmy for the 1983 model year, below the full-size Blazer and Jimmy models. This situation lasted into the early 1990s. GMC first rebadged the full-size Jimmy as the 'Yukon' in 1991. Chevrolet however waited until 1994, when they rebadged the redesigned mid-size S-10 Blazer as their 'new Blazer', while renaming the full-size Blazer as the 'Tahoe'. The name Tahoe refers to the rugged and scenic area surrounding Lake Tahoe in the western United States. The name Yukon refers to the Yukon territory of northern Canada. For the 1995 model year, the Tahoe and Yukon gained a new, longer 4-door model, slotting in size between the 2-door models and the longer wheelbase, higher passenger capacity Chevrolet Suburban and its newly named GMC 'Yukon XL' twin.The Tahoe is sold in North America, parts of Asia such as the Philippines and the Middle East, plus other countries including Bolivia, Chile, Peru, Colombia, Ecuador, and Angola as a left-hand drive vehicle. The Yukon is only sold in North America and the Middle East.The Chevrolet Tahoe and GMC Yukon currently serve as a part of General Motors' full-size SUV family. Lengthened wheelbase models are available for both as the Suburban for Chevrolet and Yukon XL for GMC. A luxury Denali model joined the Yukon lineup in 1998 for the 1999 model year. As of 2001, a Denali version of the Yukon XL has also been available as the Yukon XL Denali. The Cadillac Escalade is closely related to the Denali models of the Yukon. As of February 2014, the 2014 Tahoe was the top-ranked Affordable Large SUV in U.S. News & World Report's rankings.The Tahoe's main competition comes from the Ford Expedition, but it also competes with the Toyota Sequoia and Nissan Armada.",
    "Kia Corporation (commonly known as Kia, but stylized as KIΛ) (Korean: 기아; Hanja: 起亞; RR: Gia; MR: Kia, IPA: [ki.a]; formerly known as Kyungsung Precision Industry and Kia Motors Corporation) is a South Korean multinational automobile manufacturer headquartered in Seoul, South Korea. It is South Korea's second largest automobile manufacturer after parent company Hyundai Motor Company, with sales of over 2.8 million vehicles in 2019. As of December 2015, the Kia Corporation is minority owned by Hyundai, which holds a 33.88% stake valued at just over US\$6 billion. Kia in turn is a minority owner of more than twenty Hyundai subsidiaries ranging from 4.9% up to 45.37%, totaling more than US\$8.3 billion.",
    "Audi AG (German: [ˈaʊ̯di ʔaːˈɡeː] (About this soundlisten)) (commonly referred to as Audi) is a German automotive manufacturer of luxury vehicles headquartered in Ingolstadt, Bavaria, Germany. As a subsidiary of its parent company, the Volkswagen Group, Audi produces vehicles in nine production facilities worldwide.The origins of the company are complex, going back to the early 20th century and the initial enterprises (Horch and the Audiwerke) founded by engineer August Horch; and two other manufacturers (DKW and Wanderer), leading to the foundation of Auto Union in 1932. The modern era of Audi essentially began in the 1960s when Auto Union was acquired by Volkswagen from Daimler-Benz. After relaunching the Audi brand with the 1965 introduction of the Audi F103 series, Volkswagen merged Auto Union with NSU Motorenwerke in 1969, thus creating the present-day form of the company.The company name is based on the Latin translation of the surname of the founder, August Horch. Horch, meaning 'listen' in German, becomes audi in Latin. The four rings of the Audi logo each represent one of four car companies that banded together to create Audi's predecessor company, Auto Union. Audi's slogan is Vorsprung durch Technik, meaning 'eing Ahead through Technology'. Audi, along with fellow German marques BMW and Mercedes-Benz, is among the best-selling luxury automobile brands in the world.",
    "Opel Automobile GmbH (German pronunciation: [ˈoːpl̩]), usually shortened to Opel, is a German automobile manufacturer which has been a subsidiary of Stellantis since 16 January 2021. It was owned by General Motors from 1929 until 2017 and the PSA Group, a predecessor of Stellantis, from 2017 until 2021. Opel vehicles are sold in the British market under the Vauxhall brand. Some Opel vehicles were badge-engineered in Australia under the Holden brand until 2020 and in North America and China under the Buick, Saturn, and Cadillac brands.Opel traces its roots to a sewing machine manufacturer founded by Adam Opel in 1862 in Rüsselsheim am Main. The company began manufacturing bicycles in 1886 and produced its first automobile in 1899. After listing on the stock market in 1929, General Motors took a majority stake in Opel and then full control in 1931, establishing an American ownership of the German automaker for nearly 90 years.In March 2017, PSA agreed to acquire Opel, the British twin sister brand Vauxhall and the European auto lending business from General Motors for €2.2 billion, making the French automaker the second biggest in Europe, after Volkswagen.Opel is still headquartered in Rüsselsheim am Main. The company designs, engineers, manufactures and distributes Opel-branded passenger vehicles, light commercial vehicles, and vehicle parts; together with its English sister marque Vauxhall, they are present in over 60 countries around the world.",
    "The Bugatti Veyron EB 16.4 is a mid-engine sports car, designed and developed in France by the Volkswagen Group and Bugatti and manufactured in Molsheim, France, by French automobile manufacturer Bugatti. It was named after the racing driver Pierre Veyron.The original version has a top speed of 407 km/h (253 mph). It was named Car of the Decade and best car award (2000–2009) by the BBC television programme Top Gear. The standard Bugatti Veyron also won Top Gear's Best Car Driven All Year award in 2005.The Super Sport version of the Veyron is one of the fastest street-legal production cars in the world, with a top speed of 431.072 km/h (267.856 mph). The Veyron Grand Sport Vitesse was the fastest roadster in the world, reaching an averaged top speed of 408.84 km/h (254.04 mph) in a test on 6 April 2013.The Veyron's chief designer was Hartmut Warkuß and the exterior was designed by Jozef Kabaň of Volkswagen, with much of the engineering work being conducted under the guidance of chief technical officer Wolfgang Schreiber. The Veyron includes a sound system designed and built by Burmester Audiosysteme.Several special variants have been produced. In December 2010, Bugatti began offering prospective buyers the ability to customise exterior and interior colours by using the Veyron 16.4 Configurator application on the marque's official website. The Bugatti Veyron was discontinued in late 2014, but special edition models continued to be produced until 2015.",
  ];
}
